// src/frontend/src/components/NftCard.jsx
import React, { useState, useEffect } from "react";
import { imageCache } from "../utils/imageCache";

function NftCard({ nft, onClick }) {
  const [imageLoaded, setImageLoaded] = useState(false);
  const [imageSrc, setImageSrc] = useState("");

  useEffect(() => {
    if (!nft?.image) {
      setImageLoaded(true);
      setImageSrc("");
      return;
    }
    let isMounted = true;
    const loadImage = async () => {
      try {
        const cachedResponse = await imageCache.getCachedImage(nft.image);
        if (cachedResponse) {
          const blob = await cachedResponse.blob();
          if (isMounted) {
            setImageSrc(URL.createObjectURL(blob));
            setImageLoaded(true);
          }
        } else {
          setImageSrc(nft.image);
          const img = new window.Image();
          img.onload = () => {
            if (isMounted) setImageLoaded(true);
            imageCache.cacheImage(nft.image);
          };
          img.onerror = () => {
            if (isMounted) setImageLoaded(true);
          };
          img.src = nft.image;
        }
      } catch (error) {
        setImageSrc(nft.image);
        setImageLoaded(true);
      }
    };
    setImageLoaded(false);
    setImageSrc("");
    loadImage();
    return () => { isMounted = false; };
  }, [nft]);

  return (
    <div className="nft-card" onClick={() => onClick(nft)}>
      <div className="relative w-full" style={{ aspectRatio: '1 / 1', overflow: 'hidden' }}>
        {nft.image ? (
          <>
            <img
              src={imageSrc}
              alt={nft.name}
              className={`nft-card-image w-full h-full object-cover ${imageLoaded ? 'opacity-100' : 'opacity-0'}`}
              style={{ transition: 'opacity 0.3s ease', width: '100%', height: '100%', display: 'block', objectFit: 'cover' }}
            />
            {!imageLoaded && (
              <div className="absolute inset-0 flex items-center justify-center bg-gray-100 bg-opacity-50">
                <div className="loading-spinner w-8 h-8"></div>
              </div>
            )}
          </>
        ) : (
          <div className="w-full h-full flex items-center justify-center text-muted bg-gradient-to-br from-gray-100 to-gray-200">
            No Image
          </div>
        )}
        <div className="glass-badge absolute top-sm right-sm">
          #{nft.id}
        </div>
      </div>
      <div className="p-md w-full" style={{ maxWidth: '100%' }}>
        <h3 className="text-xs font-medium text-primary nft-card-title" style={{ 
          fontSize: 'clamp(0.65rem, 0.8vw, 0.85rem)', 
          lineHeight: '1.2', 
          wordWrap: 'break-word', 
          overflowWrap: 'break-word'
        }}>
          {nft.name}
        </h3>
      </div>
    </div>
  );
}

export default NftCard;

// src/frontend/src/components/NftCard.vue
<template>
  <div class="nft-card" @click="$emit('click')">
    <div class="nft-card-image-container">
      <img
        v-if="nft.image"
        :src="imageSrc"
        :alt="nft.name"
        class="nft-card-image"
        :class="{ 'image-loaded': imageLoaded, 'image-loading': !imageLoaded }"
      />
      <div
        v-if="!imageLoaded && nft.image"
        class="nft-card-loading"
      >
        <div class="loading-spinner"></div>
      </div>
      <div
        v-if="!nft.image"
        class="nft-card-no-image"
      >
        No Image
      </div>
      <div class="glass-badge nft-card-badge">
        #{{ nft.id }}
      </div>
    </div>
    <div class="nft-card-content">
      <h3 class="nft-card-title">
        {{ nft.name }}
      </h3>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'

interface NftAttribute {
  trait_type: string
  value: string | number
}

interface Nft {
  id: string
  name: string
  description: string
  image: string
  attributes: NftAttribute[]
  metadataUrl: string | null
}

interface Props {
  nft: Nft
}

const props = defineProps<Props>()
defineEmits<{
  click: []
}>()

const imageLoaded = ref(false)
const imageSrc = ref('')

// Image loading logic
watch(() => props.nft?.image, async (newImage) => {
  if (!newImage) {
    imageLoaded.value = true
    imageSrc.value = ''
    return
  }
  
  imageLoaded.value = false
  imageSrc.value = ''
  
  try {
    // Try to get from cache first
    const cachedResponse = await imageCache.getCachedImage(newImage)
    if (cachedResponse) {
      const blob = await cachedResponse.blob()
      imageSrc.value = URL.createObjectURL(blob)
      imageLoaded.value = true
    } else {
      // Load from network
      imageSrc.value = newImage
      const img = new window.Image()
      img.onload = () => {
        imageLoaded.value = true
        imageCache.cacheImage(newImage)
      }
      img.onerror = () => {
        imageLoaded.value = true
      }
      img.src = newImage
    }
  } catch (error) {
    imageSrc.value = newImage
    imageLoaded.value = true
  }
}, { immediate: true })

// Simple image cache utility (you can enhance this)
const imageCache = {
  async getCachedImage(url: string) {
    try {
      const cache = await caches.open('nft-images')
      return await cache.match(url)
    } catch {
      return null
    }
  },
  
  async cacheImage(url: string) {
    try {
      const cache = await caches.open('nft-images')
      await cache.add(url)
    } catch {
      // Ignore cache errors
    }
  }
}
</script>

<style scoped>
/* NFT Card Component */
.nft-card {
  position: relative;
  background: rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
  border-radius: var(--radius-xl);
  overflow: hidden;
  cursor: pointer;
  transition: all 0.3s ease;
  transform: translateY(0);
  animation: cardEntrance 0.6s ease-out;
  border: 1px solid rgba(255, 255, 255, 0.1);
}

.nft-card:hover {
  transform: translateY(-8px) scale(1.02);
  box-shadow: 0 50px 100px -20px rgba(0, 0, 0, 0.25), 0 0 20px rgba(139, 92, 246, 0.3);
  border-color: rgba(139, 92, 246, 0.3);
}

.nft-card:hover::before {
  opacity: 1;
}

.nft-card:hover .nft-card-image {
  transform: scale(1.08);
}

.nft-card:hover .nft-card-badge {
  transform: scale(1.1);
  background: rgba(139, 92, 246, 0.15);
  border-color: rgba(139, 92, 246, 0.3);
}

.nft-card:hover .nft-card-content {
  background: rgba(139, 92, 246, 0.15);
}

.nft-card.loading {
  pointer-events: none;
  opacity: 0.7;
}

@keyframes cardEntrance {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.nft-card-image-container {
  position: relative;
  width: 100%;
  aspect-ratio: 1 / 1;
  overflow: hidden;
  border-radius: var(--radius-xl) var(--radius-xl) 0 0;
  background: rgba(255, 255, 255, 0.05);
}

.nft-card-image {
  width: 100%;
  height: 100%;
  display: block;
  object-fit: cover;
  transition: transform 0.5s ease;
  will-change: transform;
}

.nft-card-loading {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(255, 255, 255, 0.05);
  backdrop-filter: blur(4px);
  -webkit-backdrop-filter: blur(4px);
}

.nft-card-loading .loading-spinner {
  width: 32px;
  height: 32px;
  border-width: 2px;
}

.nft-card-no-image {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--text-muted);
  background: linear-gradient(135deg, #1f2937, #374151);
  font-size: var(--font-size-sm);
  font-weight: 500;
  letter-spacing: 0.05em;
}

.nft-card-badge {
  position: absolute;
  top: var(--spacing-sm);
  right: var(--spacing-sm);
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  border-radius: var(--radius-md);
  padding: var(--spacing-xs) var(--spacing-sm);
  font-size: var(--font-size-xs);
  font-weight: 600;
  color: var(--text-white);
  letter-spacing: 0.05em;
  transition: all 0.3s ease;
  z-index: 2;
}

.nft-card-content {
  padding: var(--spacing-lg);
  background: rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  transition: all 0.3s ease;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
}

.nft-card-title {
  font-size: clamp(0.875rem, 1.2vw, 1rem);
  font-weight: 600;
  color: var(--text-primary);
  line-height: 1.2;
  letter-spacing: -0.025em;
  margin: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  transition: color 0.2s ease;
}

.nft-card:hover .nft-card-title {
  color: var(--text-white);
}
</style>
